### PR TITLE
Add polar bears.

### LINKED ISSUE #388: [1.12.2] Polar Bears not registered in LootTableHelper
Minecraft: 1.12.2
JER: 1.12.2-0.9.2.60
Forge: 14.23.5.2859

Polar Bears are not registered in 1.12.2. Rather amusingly, after seven years gone unnoticed I discovered this due to a personal Modpack I am building; it requires a way to get fish without water. I am willing to test and submit a pull request if needed. I understand if it is impractical to update the branch after all this time and am comfortable using a mod to patch this using the API. Thank you for any communication.

### PR DESCRIPTION
**Pull request by unnecessary1234**
Let me know if you have trouble building, I had to change build.gradle on my machine to download a dependency. I apologize for being late, but simple as the change, I wanted to test it.

Fixes #388

### CODE REVIEW

**Comment by way2muchnoise** [comment]
Thanks for the PR, lets see if it builds automatically and publishes to CF.

**Comment by unnecessary1234** [comment]
How do I know if it builds? I tried to check Travis CI, but it said you have had no credits for about a month. Thank you for helping with this.

**Comment by way2muchnoise** [comment]
Yeah, noticed that yesterday. Reached out to Travis CI for OSS credits which I got now, so I'm triggering custom builds right now :)

**Comment by way2muchnoise** [comment]
Trying to solve build issues:
 - https://app.travis-ci.com/github/way2muchnoise/JustEnoughResources/builds/261514776
 - https://app.travis-ci.com/github/way2muchnoise/JustEnoughResources/jobs/598177426

Seems like a dependency issue with JEI, please create a new PR if you know how to solve it 😄 
Otherwise I'll just ask @mezz where the 1.12.2 builds of JEI are hiding 👀

**Pull request merged**
