### PR TITLE
Fix for proper comparison of WatchableData with DataWatchers

### PR DESCRIPTION
**Pull request by P3pp3rF1y**
Updated the proper lines with new Byte instances the same way they are used in the vanilla entities. 
That's also the reason why Guardian ones are untouched as they actually use integer in the EntityGuardian.

BTW: don't mind my comment from yesterday regarding comparing to byteValue. It was obviously too late for me to think straight :D

### CODE REVIEW

**Comment by way2muchnoise** [comment]
Is there any reason you'd need to cast and box them?

**Comment by way2muchnoise** [comment]
Tested it and there is no need to cast an box so I opted to just cast. Might reimplement so it uses the super type `Number` and just compares the double value for it as that would make it so that it doesn't matter what type you use.

**Comment by P3pp3rF1y** [comment]
What I have done in there with boxing was just the same thing that vanilla does so I guess there was no really good reason for that now that you have tested it's not needed. :D

**Comment by way2muchnoise** [comment]
@P3pp3rF1y I released a [hotfix build](https://github.com/way2muchnoise/JustEnoughResources/releases/tag/0.3.4) for this issue/PR

**Comment by P3pp3rF1y** [comment]
Thanks for letting me know. It's now added in the latest release of Reliquary on curseforge. 
And in case you wanted to point people to example implementation you can point them to this file
https://github.com/P3pp3rF1y/Reliquary/blob/master/src/main/java/xreliquary/compat/jer/JERCompat.java

**Pull request closed without merging**
