### PR TITLE
Made plant entries more customizable and compatible, fixes main issue from #213

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
- The age property is no longer hardcoded, but instead checks for any property named 'age'. One of example where it matters are beetroot and nether wart, which have different growth time (both of which are added as entries).
- Additionally, it's possible to override it with manually specified property. One example where just checking for 'age' property wouldn't work is Extra Utilities 2, which is using a property named 'growth'.

- It's now possible to directly provide BlockState to PlantEntry for cases where it wouldn't be possible to only provide IPlantable. An example of where it would be useful is Harvestcraft mod - its fruits and special logs do not implement IPlantable.
- In case if BlockState is not provided, the normal check for plant entry is done, which if it's not provided as well will fallback to getting default state of the ItemStack. No matter which case we'll fall into, a check for the 'age' property will be made (if not provided before).

### CODE REVIEW

**Comment by exploder1531** [comment]
Just to be completely clear about these changes - I originally made them for 1.12.2 and tested them there. That's why I'm mentioning Extra Utilities 2 and Harvestcraft as examples for mods that it would affect.

**Comment by SokyranTheDragon** [comment]
I've decided to add sweet berries as I've realized that it does have growth states as well

**Comment by way2muchnoise** [comment]
Could you change the revision in the version number for this change? See https://github.com/way2muchnoise/JustEnoughResources/blob/master/gradle.properties#L6

**Comment by way2muchnoise** [comment]
Thx for the PR :)

**Pull request merged**
